name: larapaper
services:
    app:
        image: ghcr.io/usetrmnl/larapaper:latest
        ports:
            - "4567:8080"
        environment:
            # Generate the APP_KEY with `echo "base64:$(openssl rand -base64 32)"`
            # - APP_KEY=CwMGn/77mWhrG+7GYkvUn8flXXnpbT/ryTaL5dX/Gfo=
            # Base URL of the application
            - APP_URL="http://192.168.2.246:4567"
            - PHP_OPCACHE_ENABLE=1
            - TRMNL_PROXY_REFRESH_MINUTES=15
            - DB_DATABASE=database.sqlite
        volumes:
            - /srv/docker/larapaper/database/:/var/www/html/database/storage
            - /srv/docker/larapaper/storage/:/var/www/html/storage/app/public/images/generated
        restart: unless-stopped
